config/routes.rb
LandingPageEng::Engine.routes.draw do
  match '/landing_pages/sitemap', to: 'landing_pages#sitemap'
  match '/products/sitemap', to: 'products#sitemap'
  resources :products
  resources :landing_pages
  match ":slug", to: "landing_pages#route"
  match "/gift/:slug", to: "products#route"
end

app/models/landing_page_eng/landing_page.rb
require 'redcarpet'

module LandingPageEng
	class LandingPage < ActiveRecord::Base
		attr_accessible :slug, :meta_description, :title, :meta_keywords, :body, :slide_show_slides_attributes, 
						:picture_link_texts_attributes, :call_to_action_url, :template

		has_many :slide_show_slides, :dependent => :destroy, :class_name => "LandingPageEng::SlideShowSlide"
		has_many :picture_link_texts, :dependent => :destroy, :class_name => "LandingPageEng::PictureLinkText"

		accepts_nested_attributes_for :slide_show_slides, allow_destroy: true
		accepts_nested_attributes_for :picture_link_texts, allow_destroy: true

		validates :meta_description, presence: true

		def body
			markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
			markdown.render(read_attribute(:body)).html_safe
		end
	end
end

app/models/landing_page_eng/picture_link_text.rb
module LandingPageEng
  class PictureLinkText < ActiveRecord::Base
	belongs_to :landing_page
    attr_accessible :body, :image, :zoom_image, :landing_page_id, :link, :title, :tags, :categories

	mount_uploader :image, LandingPageEng::LandingPageEngPictureLinkTextImageUploader 

	def body
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
		markdown.render(read_attribute(:body)).html_safe
	end
  end
end

app/models/landing_page_eng/price.rb
module LandingPageEng
	class Price < ActiveRecord::Base
		belongs_to :product
	end
end

app/models/landing_page_eng/product.rb
require 'redcarpet'

module LandingPageEng
	class Product < ActiveRecord::Base
		CATEGORIES = ["Animals",
		"Apparel & Accessories",
		"Arts & Entertainment",
		"Baby & Toddler",
		"Business & Industrial",
		"Cameras & Optics",
		"Electronics",
		"Food, Beverages & Tobacco",
		"Furniture",
		"Hardware",
		"Health & Beauty",
		"Home & Garden",
		"Luggage & Bags",
		"Mature",
		"Media",
		"Office Supplies",
		"Religious & Ceremonial",
		"Software",
		"Sporting Goods",
		"Toys & Games",
		"Vehicles & Parts"]

		attr_accessible :categories, :tags, :description, :details, :name, :picture_link_texts_attributes, 
		:prices_attributes, :target_affiliates_attributes, :slug, :brand, :department

		has_many :prices
		has_many :picture_link_texts
		has_many :target_affiliates

		accepts_nested_attributes_for :picture_link_texts, allow_destroy: true
		accepts_nested_attributes_for :prices, allow_destroy: true
		accepts_nested_attributes_for :target_affiliates, allow_destroy: true

		validates :name,  presence: true, length: { maximum: 50 }
		validates :description, presence: true

		# Return the lowest known price for a given product or nil
		def price
			begin
				target_affiliates = self.target_affiliates
				target_affiliates[0].price
			rescue Exception => e
				nil
			end
		end

		def description
			markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
			markdown.render(read_attribute(:description)).html_safe
		end

		def details
			markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
			markdown.render(read_attribute(:details)).html_safe
		end	

	end
end

app/models/landing_page_eng/slide_show_image.rb
module LandingPageEng
	class SlideShowImage < ActiveRecord::Base
		belongs_to :landing_page 
		attr_accessible :image, :landing_page_id

		#validates :landing_page_id, :presence => true, :numericality => { :only_integer => true }
		validates :image, :presence => true

		mount_uploader :image, LandingPageEngSlideShowImageUploader

	end
end

app/models/landing_page_eng/slide_show_slide.rb
require 'redcarpet'

module LandingPageEng
	class SlideShowSlide < ActiveRecord::Base
		belongs_to :landing_page 
		attr_accessible :image, :title, :tagline, :body, :call_to_action_url, :landing_page_id

		#validates :landing_page_id, :presence => true, :numericality => { :only_integer => true }
		validates :image, :presence => true

		mount_uploader :image, LandingPageEng::LandingPageEngSlideShowImageUploader

		def body
			markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
			markdown.render(read_attribute(:body)).html_safe
		end
	end
end

app/models/landing_page_eng/target_affiliate.rb
module LandingPageEng
  class TargetAffiliate < ActiveRecord::Base
    attr_accessible :product_id, :name, :price, :url
  end
end

app/controllers/landing_page_eng/application_controller.rb
module LandingPageEng
  class ApplicationController < ActionController::Base
  end
end

app/controllers/landing_page_eng/landing_pages_controller.rb
#require_dependency "landing_page_eng/application_controller"

module LandingPageEng
	class LandingPagesController < LandingPageEng::ApplicationController
		include LandingPagesControllerMixin
		# GET /landing_pages
		# GET /landing_pages.json
		def index
			@landing_pages = LandingPage.all

			respond_to do |format|
				format.html # index.html.erb
				format.json { render json: @landing_pages }
			end
		end

		def sitemap
			@landing_pages = LandingPage.all

			respond_to do |format|
				format.html 
				format.xml  
			end
		end

		def route
			@landing_page = LandingPage.find_by_slug(params[:slug])

			render :show
		end

		# GET /landing_pages/1
		# GET /landing_pages/1.json
		def show
			@landing_page = LandingPage.find(params[:id])

			# adds instance variables 
			add_vars_based_on_template_for_show_action(@landing_page.template)

			respond_to do |format|
				format.html { render render_template(@landing_page) } # show.html.erb
				format.json { render json: @landing_page }
			end
		end

		def show_home
			@landing_page = LandingPage.where("slug = \'home-page\'").first
			add_vars_based_on_template_for_show_action(@landing_page.template, params)

			respond_to do |format|
				format.html { render render_template(@landing_page)} # show.html.erb,
				format.json { render json: @landing_page }
			end
		end
		
		# GET /landing_pages/new
		# GET /landing_pages/new.json
		def new
			logger.debug "******* paths loaded are #{Rails.application.config.assets.paths}"
			@landing_page = LandingPage.new

			respond_to do |format|
				format.html # new.html.erb
				format.json { render json: @landing_page }
			end
		end

		# GET /landing_pages/1/edit
		def edit
			@landing_page = LandingPage.find(params[:id])
		end

		# POST /landing_pages
		# POST /landing_pages.json
		def create
			@landing_page = LandingPage.new(params[:landing_page])

			respond_to do |format|
				if @landing_page.save
					format.html { redirect_to @landing_page, notice: 'Landing page was successfully created.' }
					format.json { render json: @landing_page, status: :created, location: @landing_page }
				else
					format.html { render action: "new" }
					format.json { render json: @landing_page.errors, status: :unprocessable_entity }
				end
			end
		end

		# PUT /landing_pages/1
		# PUT /landing_pages/1.json
		def update
			@landing_page = LandingPage.find(params[:id])

			respond_to do |format|
				if @landing_page.update_attributes(params[:landing_page])
					format.html { redirect_to @landing_page, notice: 'Landing page was successfully updated.' }
					format.json { head :no_content }
				else
					format.html { render action: "edit" }
					format.json { render json: @landing_page.errors, status: :unprocessable_entity }
				end
			end
		end

		# DELETE /landing_pages/1
		# DELETE /landing_pages/1.json
		def destroy
			@landing_page = LandingPage.find(params[:id])
			@landing_page.destroy

			respond_to do |format|
				format.html { redirect_to landing_pages_url }
				format.json { head :no_content }
			end
		end

		private

		def render_template(landing_page)
			if landing_page.template.blank?
				"show"
			else
				landing_page.template
			end
		end
	end
end

app/controllers/landing_page_eng/landing_pages_controller_mixin.rb
module LandingPageEng
	module LandingPagesControllerMixin
		def add_vars_based_on_template_for_show_action(template, params = {})
			case template 
				when "show" then ""	
				when "home" then 
					if params[:for].nil?
						@new_products = Product.order("updated_at DESC").limit(7)
					else
						@new_products = Product.search(tags: params[:for]).order("updated_at DESC").limit(7)
					end
				else ""
			end
		end
	end
end

app/controllers/landing_page_eng/products_controller.rb
require_dependency "landing_page_eng/application_controller"

module LandingPageEng
  class ProductsController < ApplicationController
    # GET /products
    # GET /products.json
    def index
      @products = Product.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @products }
      end
    end
  
    # GET /products/1
    # GET /products/1.json
    def show
      @product = Product.find(params[:id])
      # TODO limit the number of results to someting reasonable
      @recommended_products = Product.where("id != ?", @product.id) 

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @product }
      end
    end

    def route
      @product = Product.find_by_slug(params[:slug])
      @recommended_products = Product.where("id != ?", @product.id) 

      render :show
    end

    def sitemap
      @products = Product.all

      respond_to do |format|
        format.html 
        format.xml  
      end
    end
  
    # GET /products/new
    # GET /products/new.json
    def new
      @product = Product.new
      @categories = Product::CATEGORIES
      
      respond_to do |format|
        format.html { render layout: false } # new.html.erb
        format.json { render json: @product }
      end
    end
  
    # GET /products/1/edit
    def edit
      @product = Product.find(params[:id])
      @categories = Product::CATEGORIES
    end
  
    # POST /products
    # POST /products.json
    def create
      @product = Product.new(params[:product])
  
      respond_to do |format|
        if @product.save
          format.html { redirect_to @product, notice: 'Product was successfully created.' }
          format.json { render json: @product, status: :created, location: @product }
        else
          format.html { render action: "new" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /products/1
    # PUT /products/1.json
    def update
      @product = Product.find(params[:id])
  
      respond_to do |format|
        if @product.update_attributes(params[:product])
          format.html { redirect_to @product, notice: 'Product was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /products/1
    # DELETE /products/1.json
    def destroy
      @product = Product.find(params[:id])
      @product.destroy
  
      respond_to do |format|
        format.html { redirect_to products_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/landing_page_eng/application_helper.rb
module LandingPageEng
	module ApplicationHelper
		def link_to_add_fields(name, f, association, partial = nil)
			new_object = f.object.send(association).klass.new
			id = new_object.object_id
			fields = f.fields_for(association, new_object, child_index: id) do |builder|
				if partial.nil?
					render(association.to_s.singularize + "_fields", f: builder)
				else
					render(partial, f: builder)
				end
			end
			link_to(name, '#', class: "add_fields button", data: {id: id, fields: fields.gsub("\n", "")})
		end
	end
end

app/helpers/landing_page_eng/landing_pages_helper.rb
module LandingPageEng
	module LandingPagesHelper
		
	end
end

app/helpers/landing_page_eng/products_helper.rb
module LandingPageEng
	module ProductsHelper
		# TODO where can we put this so it is implemented only once
		
	end
end

app/views/landing_page_eng/landing_pages/_form.html.erb
<%= form_for(@landing_page, html: {multipart: true}) do |f| %>
	<% if @landing_page.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@landing_page.errors.count, "error") %> prohibited this landing_page from being saved:</h2>

			<ul>
				<% @landing_page.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :slug %><br />
		<%= f.text_field :slug %>
	</div>
	<div class="field">
		<%= f.label :template %><br />
		<%= f.text_field :template %>
	</div>
	<div class="field">
		<%= f.label :meta_keywords %><br />
		<%= f.text_area :meta_keywords, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :meta_description %><br />
		<%= f.text_area :meta_description, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_area :title, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body, rows: 10, columns: 80 %>
	</div>

	<div class="field">
	<%= f.fields_for :slide_show_slides do |builder| %>
		<%= render "slide_show_slide_fields", f: builder %>
	<% end %>
	<%= link_to_add_fields "click to add slide show image and text", f, :slide_show_slides %>
	</div>

	<div class="field">
	<%= f.fields_for :picture_link_texts do |builder| %>
		<%= render "picture_link_text_fields", f: builder %>
	<% end %>
	<%= link_to_add_fields "Click to add a picture-link-text", f, :picture_link_texts %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/landing_page_eng/landing_pages/_picture_link_text_fields.html.erb
<fieldset>
	<legend>Picture Link Text:</legend>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body, rows: 6 %>
	</div>
	<div class="field">
		<%= f.label :link %><br />
		<%= f.text_field :link, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :image %><br />
		<%= f.file_field :image %>
	</div>
	<div class="field">
		<%= f.label :tags %><br />
		<%= f.text_field :tags, rows: 2 %>
	</div>

	<%= f.hidden_field :_destroy %>
	<%= link_to "remove", "#", class: "remove_fields" %>
</fieldset>

app/views/landing_page_eng/landing_pages/_picture_link_texts.html.erb
<div class="container picture-link-texts">
	<% plts.find_all{|plt| plt.tags.include?(tag) }.each_with_index do |plt, index| %>
		<% if index % 2 == 0 %>
			<div class="picture-link-text eight columns alpha">
		<% else %>
			<div class="picture-link-text eight columns omega">
		<% end %>
		
			<% unless plt.image.blank? %>
				<div class="picture four columns alpha">
					<a href="<%= plt.link %>"><%= image_tag plt.image_url, class: 'scale-with-grid' %></a><em></em>
				</div>
			<% end %>
	
			<div class="body four columns omega">
				<% unless plt.title.blank? %><h2><%= plt.title %></h2><% end %>
				<%= plt.body %>
				<% unless plt.link.blank? %><%= link_to "read more", plt.link %><% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/landing_page_eng/landing_pages/_sitemap.html.erb
<ul>
  <% landing_pages.each do | lp | %>
  <li><a href="/lp/<%= lp.slug %>"><%= lp.title %></a></li>
  <% end %>
</ul>

app/views/landing_page_eng/landing_pages/_slide_show_slide_fields.html.erb
<fieldset>
	<legend>Slide Show Slide:</legend>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_area :title, rows: 2 %>
	</div>
	<div class="field">
		<%= f.label :tagline %><br />
		<%= f.text_area :tagline, rows: 4 %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body, rows: 6 %>
	</div>
	<div class="field">
		<%= f.label :call_to_action_url %><br />
		<%= f.text_field :call_to_action_url %>
	</div>
	<div class="field">
		<%= f.label :image %><br />
		<%= f.file_field :image %>
	</div>

	<%= f.hidden_field :_destroy %>
	<%= link_to "remove", "#", class: "remove_fields" %>
</fieldset>

app/views/landing_page_eng/landing_pages/_slide_show_slides.html.erb
<% unless landing_page.slide_show_slides.nil? %>
		<div id="slide-show-slides" >
			<% landing_page.slide_show_slides.each do |slide| %>
				<div class="slide-show-slide" style="background: url(<%= slide.image_url.to_s %>) no-repeat">
					<% unless slide.body.blank? %>
						<div class="slide-copy">
							<% unless slide.title.blank? %><h2><%= slide.title %></h2><% end %>
							<% unless slide.tagline.blank? %><h3><%= slide.tagline %></h3><% end %>
							<p><%= slide.body %></p>
							<% unless slide.call_to_action_url.blank? %>
								<a href="<%= slide.call_to_action_url %>" class="button_yellow">Find out more</a>
							<% end %>
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
	<% end %>

app/views/landing_page_eng/landing_pages/edit.html.erb
<h1>Editing landing_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @landing_page %> |
<%= link_to 'Back', landing_pages_path %>

app/views/landing_page_eng/landing_pages/index.html.erb
<h1>Listing landing_pages</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landing_pages.each do |landing_page| %>
  <tr>
    <td><%= landing_page.slug %></td>
    <td><%= link_to 'Show', landing_page %></td>
    <td><%= link_to 'Edit', edit_landing_page_path(landing_page) %></td>
    <td><%= link_to 'Destroy', landing_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landing page', new_landing_page_path %>

app/views/landing_page_eng/landing_pages/new.html.erb
<h1>New landing_page</h1>

<%= render 'form' %>

<%= link_to 'Back', landing_pages_path %>

app/views/landing_page_eng/landing_pages/show.html.erb
<% content_for :meta_description do %>
<meta name="description" content="<%= @landing_page.meta_description %>">
<% end %>


<div class="container">
	<div class="sixteen columns">
		<p id="notice"><%= notice %></p>

		<%= render partial: "slide_show_slides", locals: {landing_page: @landing_page} %>
	</div>
</div>

<div class="bg_gray add-bottom_3">
	<% unless @landing_page.picture_link_texts.nil? %>
	<div class="highlights">
		<%= render partial: 'picture_link_texts', locals: {plts: @landing_page.picture_link_texts, tag: "highlight"} %>
	</div>
	<% end %>
</div>

<section class="title-and-tagline container">
	<% unless @landing_page.body.blank? %><%= @landing_page.body %><% end %>
</section>

<div class="bg_gray add-bottom_3">
	<% unless @landing_page.picture_link_texts.nil? %>
	<%= render partial: 'picture_link_texts', locals: {plts: @landing_page.picture_link_texts, tag: "plt"} %>
	<% end %>
</div>

<%= link_to 'Edit', edit_landing_page_path(@landing_page) if (not current_user.nil?) && current_user.is_writer? %>

app/views/landing_page_eng/landing_pages/sitemap.html.erb
<h2>Chi-Town Custom Cornhole landing pages</h2>
<%= render partial: "sitemap", locals: {landing_pages: @landing_pages} %>

app/views/landing_page_eng/landing_pages/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
      <loc>http://<%= request.host_with_port %>/worst-boyfriend-birthday-gifts</loc>
      <changefreq>weekly</changefreq>
    </url>
    <url>
      <loc>http://<%= request.host_with_port %>/top-5-best-birthday-gifts-for-your-boyfriend</loc>
      <changefreq>weekly</changefreq>
    </url>

  <% @landing_pages.each do | lp | %>
  	<% unless lp.slug == 'home-page' %>
    <url>
      <loc>http://<%= request.host_with_port %>/lp/<%= lp.slug %></loc>
      <changefreq>weekly</changefreq>
    </url>
    <% end %>
  <% end %>

</urlset>